config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "items#index"
	resources :items, only: [:show, :index] do
		resources :carts, only: [:create, :show, :update] do
				resources :charges, only: [:new, :create, :index]
		end
	end
	resources :users do
		resources :images
	end
resources :orders, only: [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :order, optional: true
	belongs_to :item
	has_many :items
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	
	belongs_to :cart, optional: true
	has_many :carts
	has_many :orders, through: :carts
	  validates :title, presence: true
	  validates :description, length: { maximum: 500 }
	  validates :price, presence: true
	  validates :image_url, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :carts
	has_many :items, through: :carts
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
	 after_create :welcome_send
	   has_one :cart
	   has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :check_cart_number_for_user, only: [:create]
  def index
  end

  def show
    @cart = current_user.cart.items
  end

  def new
  end

  def create
    @cart = Cart.new(user_id: current_user.id, item_id: params[:item_id])
    carts = Cart.all
    if @cart.save
      item = Item.find(params[:item_id])
      current_user.cart.items << Item.find(params[:item_id])
      flash[:alert] =  "#{current_user.email}, vous avez ajouté  #{item.title} dans votre panier
      et Vous avez atteint le nombre de cart"
      redirect_to item_cart_path(params[:item_id], @cart.id)
    end

  end

  def edit
  end

  def update
    cart = current_user.cart.items
    cart.delete(Item.find(params[:item_id]))
    redirect_back fallback_location: '/', allow_other_host: false
  end

  def destroy
  end

private
def check_cart_number_for_user
    cart_current = Cart.where(user_id:current_user.id)
    if cart_current.length >= 1
      item = Item.find(params[:item_id])
      current_user.cart.items << Item.find(params[:item_id])
      redirect_to root_path
      flash[:success] = "#{current_user.email}, vous avez ajouté  #{item.title} dans votre panier"

    end
end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	 #after_action :create_order_and_pay, only: [:create]

	def new
		@item = find_item
		puts "s" * 120
	  puts params[:stripEmail]
	  puts params[:stripeToken]
	  puts "s" * 120
	end

	def create
	  # Amount in cents

		  @amount = find_item.price.to_i

		  customer = Stripe::Customer.create({
		    email: params[:stripeEmail],
		    source: params[:stripeToken],
		  })


		  charge = Stripe::Charge.create({
		    customer: customer.id,
		    amount: @amount,
		    description: 'Rails Stripe customer',
		    currency: 'usd',
		  })

	order = Order.new(user_id: current_user.id)
    if order.save
      flash[:success]= "Vous avez commandé et acheté #{find_item.title} avec succés. Vous avez recu un email de confirmation de votre commande"
      redirect_to root_path
    end

		rescue Stripe::CardError => e
		  flash[:error] = e.message
	redirect_to root_path
	
		end


	private
	def find_item
		Item.find(params[:item_id])
	end
	def create_order_and_pay
		if create
		redirect_to orders_path, method: :post
		end
	end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	def create
		@user= User.find(params[:user_id])
		@user.image.attach(params[:image])
		redirect_to user_path(@user.id)
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
	def index
		@items = Item.all
	end
  def show

  	@item = find_item
    @cart = Cart.find_by(user_id: current_user.id)

  end
  def update
    
  end

  private
  def find_item
  	Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

 private
  def find_item
    Item.find(params[:item_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  
   @user = User.find(params[:id])
   
  end

  def new
    @user= User.new
  end

  def create
    @user= User.new(user_params)
    @user.image.attach(params[:image])
    redirect_to @user
  end

  def update
    @user = current_user.update(user_params)
  end


  def destroy
    @user.destroy
    @user.image.purge
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :age, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for_flash(type)
		case type
			when "notice" then "alert-info"
			when "success" then "alert-success"
			when "errors" then "alert-danger"
			when "alert" then "alert-warning"
		end
	end
	def find_out_item
		Item.where(user_id: current_user.id)

	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/imas_helper.rb
module ImasHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<h1>Carts#index</h1>
<p>Find me in app/views/carts/index.html.erb</p>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<h1>Carts of <%=current_user.email%></h1>
<hr>
<div>
	<p>There are your items(s):<br></p>
<%@cart.each do |item|%>
<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">	
      <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home"><%=item.title%> qui coûte:$<%=item.price%></a>
    </div> <br>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
    	
      <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list"><%=item.description%></div>
      <a href="<%=new_item_cart_charge_path(item.id, current_user.cart.id)%>" type="button" class="btn-secondary btn-sm">Passer commande</a>
      <%=link_to "Rendre ce produit", item_cart_path(item.id, current_user.cart.id), role: "button", class: "btn-secondary btn-sm", method: :put %>
    </div>
  </div>
</div>
  <%end%>
</div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h2>Thanks, you paid <strong>$5.00</strong>!</h2>
</body>
</html>

app/views/charges/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <style type="text/css">
    body{
      background-color: #367;
    }
    #blog{
  color: #FFF;
  background-color: #808000;
  text-shadow: #FFF 0 -1px 4px, #ff0 0 -2px 10px, #ff8000 0 -10px 20px, red 0 -18px 40px;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.8);
  
  margin-top: 300px;
  margin-bottom: 100px;
  margin-right: 100px;
  margin-left: 80px;
  text-align: center;
  font-family: arial;
    }
  </style>
</head>
<body>
  <div class='card text-white bg-success mb-3' id="blog">
  <%= form_tag  item_cart_charges_path(params[:item_id], params[:cart_id]) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span class="btn btn-info">❤️❤️❤️❤️❤️<br><br><br><br> By now: $<%=@item.price%><br><br><br><br>❤️❤️❤️❤️❤️</span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="By cat on line"
          data-amount="<%=@item.price%>"
          data-currency="usd"
          data-locale="auto"></script>
<% end %>
</div>
</body>
</html>

app/views/items/_card.html.erb
<div class="card-deck">
  <div class="card">
  <%= image_tag image.image_url, class: "rounded-circle card-img-top" %>  <%=link_to "View >>", item_path(image.id), role: "button", class: "btn btn-outline-info "%>
    <div class="card-body">
      <h2 class="card-title" style="text-align:center;"><%= image.title %></h2>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
	<%@items.each do |image|%>
	<div class="box">
		<div class="imgBox">
		<h3><%=link_to item_path(image.id) do%>
		<%=image_tag image.image_url%>
		<%end%></h3>
		</div>
		<div class= "botton" style="color: white">
				<%if current_user && current_user.cart%>
				 <%=link_to "Add To cart", item_carts_path(image.id),  class: "btn-primary btn-sm", role: "button", method: :post%>
				 <%elsif current_user%>
				 <%=link_to "Add To/Creat cart", item_carts_path(image.id), class: "btn-primary btn-sm", role: "button", method: :post%>
				 <%end%>
		</div>

		<div class="details">
			<div class="containt" style="color: white">
				<h2>
					<%=link_to item_path(image.id) do%><%= image.title %>
					<%end%>
				</h2>
			</div>
		</div>

			<div class="details">
				<div class="containt">
					<%=link_to item_path(image.id) do%>
				<h2><%= image.title %><h2>
						<%end%>
				</div>
			</div>

	</div>
			<% end %>
</div>

app/views/items/show.html.erb
<div class=showcat>

<h1>The product description of:</h1>
<table>
	<p>
	<tr>
		<td>
			<h2><%= @item.title %></h2>
			<div>
				<%= image_tag @item.image_url, class: "rounded-circle" %>
			</div>
		</td>
		<td>
			<p><strong>Description: </strong><%=@item.description%></p>
			<h4>Price: <%= @item.price %> $</h4>
			<hr>
		</td>			
	</tr>
	</p>
</table>

				<%if current_user && current_user.cart%>
				 <%=link_to "Add To cart", item_carts_path(params[:id]), role: "button", class: "btn btn-info", method: :post%>
				 <a href="<%=new_item_cart_charge_path(params[:id], current_user.cart.id)%>" type="button" class="btn btn-secondary">Passer commande</a>
				 <%elsif current_user%>
				 <%=link_to "Add To/Create cart", item_carts_path(params[:id]), role: "button", class: "btn btn-info", method: :post%>
				 <%end%>




</div>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<%=render "layouts/form"%>

app/views/users/new.html.erb
	Nom: <br>
	<input type="text" name="last_name"> <br>
	Prénom: <br>
	 <input type="text" name="first_name"> <br>
	Age: <br>
	<input type="text" name="age"><br>
	Ville: <br>
	<input type="text" name="city"> <br>
	<input type="submit" value="Submit">
	</form> 
	

<div>
	<form action="/activestorage.js" > 
		<img class="pdp" src="upload/image.png" width="200" height="200" />
		<input type="file" name="attachments" value="photo de profil" action="upload"> <br>
		
<input type="file" name="image" value="photo de profil"> <br>
 <input name="Submit" type="submit" value="Upload image">
<br>

<div>
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

</div>

app/views/users/show.html.erb
<%=render "layouts/profile"%>