config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "items#index"
	resources :items, only: [:show, :index] do
		resources :carts, only: [:create, :show, :update] do
				resources :charges, only: [:new, :create, :index]
		end
	end
	resources :users do
		resources :images
	end
resources :orders, only: [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :order, optional: true
	belongs_to :item
	has_many :items
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	
	belongs_to :cart, optional: true
	has_many :carts
	has_many :orders, through: :carts
	  validates :title, presence: true
	  validates :description, length: { maximum: 500 }
	  validates :price, presence: true
	  validates :image_url, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :carts
	has_many :items, through: :carts
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
	 after_create :welcome_send
	   has_one :cart
	   has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :check_cart_number_for_user, only: [:create]
  def index
  end

  def show
    @cart = current_user.cart.items
  end

  def new
  end

  def create
    @cart = Cart.new(user_id: current_user.id, item_id: params[:item_id])
    carts = Cart.all
    if @cart.save
      item = Item.find(params[:item_id])
      current_user.cart.items << Item.find(params[:item_id])
      flash[:alert] =  "#{current_user.email}, vous avez ajouté  #{item.title} dans votre panier
      et Vous avez atteint le nombre de cart"
      redirect_to item_cart_path(params[:item_id], @cart.id)
    end

  end

  def edit
  end

  def update
    cart = current_user.cart.items
    cart.delete(Item.find(params[:item_id]))
    redirect_back fallback_location: '/', allow_other_host: false
  end

  def destroy
  end

private
def check_cart_number_for_user
    cart_current = Cart.where(user_id:current_user.id)
    if cart_current.length >= 1
      item = Item.find(params[:item_id])
      current_user.cart.items << Item.find(params[:item_id])
      redirect_to root_path
      flash[:success] = "#{current_user.email}, vous avez ajouté  #{item.title} dans votre panier"

    end
end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	def create
		@user= User.find(params[:user_id])
		@user.image.attach(params[:image])
		redirect_to user_path(@user.id)
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
	def index
		@items = Item.all
	end
  def show

  	@item = find_item
    @cart = Cart.find_by(user_id: current_user.id)

  end
  def update
    
  end

  private
  def find_item
  	Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

 private
  def find_item
    Item.find(params[:item_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  
   @user = User.find(params[:id])
   
  end

  def new
    @user= User.new
  end

  def create
    @user= User.new(user_params)
    @user.image.attach(params[:image])
    redirect_to @user
  end

  def update
    @user = current_user.update(user_params)
  end


  def destroy
    @user.destroy
    @user.image.purge
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :age, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for_flash(type)
		case type
			when "notice" then "alert-info"
			when "success" then "alert-success"
			when "errors" then "alert-danger"
			when "alert" then "alert-warning"
		end
	end
	def find_out_item
		Item.where(user_id: current_user.id)

	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/imas_helper.rb
module ImasHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<%flash.each do |type, message|%>

<div class="alert <%=bootstrap_class_for_flash(type)%> alert-dismissible fade show" role="alert">
  <%=message%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end%>

app/views/layouts/_footer.html.erb
<!--
	<p>Reseau sociaux : <br>
	Catch on Facebook - <a href="">@</a>
	</p>
-->
	
	

app/views/layouts/_form.html.erb
<h2>Modifier votre identité</h2>
<% if  @user.image.attached? %>
<span>
<%= image_tag @user.image , class: 'dit' %>
</span>
<% else%>
<p> Il n'y a pas photo de profil </p>
<% end%>




<div class='edi'>
	<%=form_for @user , url: user_path(@user.id) do |f|%>
	<div>
		<label>Nom :</label>
		<%=f.text_field :last_name , class: "input"%>
	</div>
	<div>
		<label>Prénom :</label>
		<%=f.text_field :first_name, class: "input"%>
	</div>
	<div>
		<label>Age :</label>
		<%=f.number_field :age, class: "input"%>
	</div>
	<div>
		<label>Ville :</label>
		<%=f.text_field :city, class: "input"%>
	</div>
	<div>
		<%=f.submit%>
	</div>
<%end%>
</div>

app/views/layouts/_navbar.html.erb
<nav id="navtheme" class="navbar navbar-dark bg-dark">
  <form class="form-inline">
      <%= link_to "Item-Home", root_path, class: "btn btn-outline-success navbar-brand", role: "button"%>
      <%if user_signed_in? && current_user.cart%>

      <%= link_to "<i class='fas fa-cart-arrow-down'><small> <span class='badge badge-light' >My Cart</span></small></i>".html_safe, item_cart_path(current_user.cart.items[0].id, current_user.cart.id), class: 'btn btn-outline-info btn-sm navbar-brand', role: "button", style: "opacity: 1.2"%>
      <%end%>
  </form>
  <ul class="bandhead">
<li class="drop">
  <a href="javascript:void(0)" class="btn-outline-primary btn-sm">Share</a>
  <div class="drop-content">
    <a href="#">facebook</a>
    <a href="#">twitter</a>
    <a href="#">youtube</a>
  </div>
</li>
</ul>

  <% if user_signed_in?%>
      <div class="btn-group">
      <button type="button" class="btn btn-info">User</button>
      <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <div class="dropdown-menu">
          <%=link_to "Mon profil", user_path(current_user.id), class:"dropdown-item"%>
          <%=link_to "Editer profil", edit_user_path(current_user.id), class:"dropdown-item" %>
         <%=link_to "Se deconnecter",destroy_user_session_path, method: :delete, class:"dropdown-item"%>
         <div class="dropdown-divider"></div>
        </div>
      </div>
<%else%>
<div class="btn-group">
      <button type="button" class="btn btn-info">User</button>
      <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
      </button>
    <div class="dropdown-menu">
      <%=link_to "S'inscrire", new_user_registration_path, class:"dropdown-item"%>
      <%=link_to "Se connecter", new_user_session_path, class:"dropdown-item"%>
      <div class="dropdown-divider"></div>
  </div>
<%end%>
</nav>

app/views/layouts/_profile.html.erb
	<div class="container">

   <h1>E-profil</h1> <br> <br>
   <% if  @user.image.attached? %>
<%= image_tag @user.image %>
<% else%> 
<p><br><br> <b>vous n'avez pas encore un photo de profil</b> </p>

   <h1>E-profil</h1>
   <% if  @user.image.attached? %>
<%= image_tag @user.image %>
<% else%>
<p> vous n'avez pas encore un photo de profil </p>

<% end%>
<br>
<%= form_tag user_images_path(@user.id), multipart: true do%>
<%= file_field_tag :image %>
<%= submit_tag "Upload image"%>

<%end%>	<div>
<a href="/users/edit">Modifier email</a> <br>
<a href=" /users/<%=@user.id%>/edit">Modifier profil</a>
  
</div>
		<div>
			<h3> A propos de moi </h3>
			<div class="content_user">
				<br><b> Mon prénom : </b> <%= @user.last_name%>
				<br><b>	Mon nom de famille: </b> <%= @user.first_name%>
				<br><b>Mon age actuel: </b><%= @user.age%>
			 	<br><b>Ville actuelle: </b>	<%= @user.city%>
			 </div>
		</div>
		</div>
		

<%end%>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineStore</title>    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="app/assets/stylesheet/application.css" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- for show-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-rtJEYb85SiYWgfpCr0jn174XgJTn4rptSOQsMroFBPQSGLdOC5IbubP6lJ35qoM9" crossorigin="anonymous">
  </head>
  <body>   
    <%=render "layouts/navbar"%>
    <%=render "layouts/flash"%>

    <%if current_user%>
<div >
  <small id="checkuser">Vous êtes connecté sous: <br><%=current_user.email%></small>
</div>
<%else%>
  <small>Vous êtes deconnecté</small>
<%end%>
    <%= yield %>
  </body>
  <footer>
     <%=render "layouts/footer" %>
  </footer>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>